version: "3.9"

networks:
  koji:


secrets:
  # Don't forget to copy/modify the `./secrets/*.dummy` files and remove the extension
  minio_user:
    file: ./secrets/minio-user
  minio_password:
    file: ./secrets/minio-password
  postgres_user:
    file: ./secrets/postgres-user
  postgres_password:
    file: ./secrets/postgres-password

services:
  # S3 compatible object storage
  minio:
    image: minio/minio
    ports:
      - ${MINIO_PORT}:9000 # Syntax: [host_port]:[container_port]
      - ${MINIO_CONSOLE_PORT}:9001
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_password
    networks:
      - koji
    secrets:
      - minio_user
      - minio_password
    volumes:
      - ./minio-data:/data # Syntax: [host_path]:[container_path]

  # PostgreSQL database for most Koji projects
  postgres:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432 # Syntax: [host_port]:[container_port]
    environment:
      POSTGRES_DB: ${POSTGRES_NAME} # default created database
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - koji
    secrets:
      - postgres_user
      - postgres_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Syntax: [host_path]:[container_path]
