version: "3.9"

networks:
  koji:


services:
  # Visualization dashboard, used in Acrelec Recommendation Systems
  metabase:
    image: metabase/metabase
    ports:
      - ${PORT_METABASE}:3000 # Syntax: [host_port]:[container_port]
    depends_on:
      - timescale
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - koji
    volumes:
      - ./metabase-data:/metabase-data

  # S3 compatible object storage
  minio:
    image: minio/minio
    ports:
      - ${PORT_MINIO}:9000 # Syntax: [host_port]:[container_port]
      - ${PORT_MINIO_CONSOLE}:9001 # Syntax: [host_port]:[container_port]
    command: server --console-address ":9001" /data
    env_file:
      - .env
    networks:
      - koji
    volumes:
      - ./minio-data:/data # Syntax: [host_path]:[container_path]

  # PostgreSQL database for most Koji projects
  postgres:
    image: postgres:alpine
    ports:
      - ${PORT_POSTGRES}:5432 # Syntax: [host_port]:[container_port]
    env_file:
      - .env
    networks:
      - koji
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # Syntax: [host_path]:[container_path]

  # A postgres database for analytics, used in Acrelec Recommendation Systems
  timescale:
    image: timescale/timescaledb:latest-pg12
    ports:
      - ${PORT_TIMESCALE}:5432 # Syntax: [host_port]:[container_port]
    env_file:
      - .env
    networks:
      - koji
    volumes:
      - ./timescale-data:/var/lib/postgresql/data # Syntax: [host_path]:[container_path]
